# Don't print a new line at the start of the prompt
add_newline = false
format = '$character$directory$git_branch$git_commit$time'

# Disables the line_break module, making the prompt a single line.
[line_break]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[time]
disabled = false
