[settings]
experimental = true

[settings.status]
missing_tools = "always"

[tools]
starship = "latest"
node = "latest"
go = "latest"
jq = "latest"
pnpm = "latest"
terraform = "latest"
neovim = "latest"
